server:
  port: 9527
spring:
  application:
      name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#    routes:
#      - id: payment-service
#        #对应的服务名
#        uri: lb://CLOUD-PAYMENT-SERVICE
#        predicates:
#          -Path=/**
      # http://localhost:9527/CLOUD-PAYMENT-SERVICE/payment/get/1
  redis:
    host: 192.168.4.115
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.gjt.mm.mysql.Driver
      url: jdbc:mysql://localhost:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.example.project.entities



eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    fetch-registry: true
    #是否从EurekaServer抓取已有注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/, http://eureka7002.com:7002/eureka/
  instance:
    #服务在EurekaServer上的显示名称
    instance-id: cloud-gateway
    #访问路径可以显示IP地址
    prefer-ip-address: true

#开启端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
