server:
  port: 80

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    fetch-registry: true
    #是否从EurekaServer抓取已有注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/, http://eureka7002.com:7002/eureka/
  instance:
      #服务在EurekaServer上的显示名称
      instance-id: consumer-feign80
      #访问路径可以显示IP地址
      prefer-ip-address: true
spring:
  application:
    name: cloud-consumer-feign-order

#Feign配置超时，因为默认为1s就超时
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
#Feign开启日志级别
logging:
  level:
    com.example.project.service.PaymentFeignService: debug

