server:
  port: 80

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    fetch-registry: true
    #是否从EurekaServer抓取已有注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/, http://eureka7002.com:7002/eureka/
  instance:
      #服务在EurekaServer上的显示名称
      instance-id: consumer-feign-hystrix80
      #访问路径可以显示IP地址
      prefer-ip-address: true
spring:
  application:
    name: cloud-consumer-feign-hystrix-order

#全局配置
# 请求连接的超时时间 默认的时间为 1 秒
ribbon:
  ConnectTimeout: 5000
# 请求处理的超时时间
  ReadTimeout: 5000
feign:
  hystrix:
    enabled: true

# feign调用时，要设置hystrix的超时时间，默认为1s
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 8000



